LIB_PATH=/home/suri/Desktop/Github/distributed_banking_application-snapshot_algorithm/Distributed Banking Application -  Global Snapshot/lib/protobuf-java-3.4.0.jar

all: clean
	mkdir bin
	mkdir bin/classes
	javac -classpath $(LIB_PATH) -d bin/classes/ src/*

clean:
	rm -rf bin/

